---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	orchestrator(orchestrator)
	worker_1(worker_1)
	worker_2(worker_2)
	worker_3(worker_3)
	aggregator(aggregator)
	__end__([<p>__end__</p>]):::last
	__start__ --> orchestrator;
	orchestrator --> worker_1;
	orchestrator --> worker_2;
	orchestrator --> worker_3;
	worker_1 --> aggregator;
	worker_2 --> aggregator;
	worker_3 --> aggregator;
	aggregator --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
